### ISSUE TITLE
tinyflow building error: converting to ‘std::unordered_map<std::basic_string<char>, std::basic_string<char> >’ from initializer list would use explicit constructor

### ISSUE THREAD

**Issue by xqdan** [tqchen/tinyflow#16]
Can be reproduced on ubuntu 14, with gcc 4.9.2

src/./op_util.h:98:82: error: converting to ‘std::unordered_map<std::basic_string<char>, std::basic_string<char> >’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >]’
                           std::unordered_map<std::string, std::string> kwarg = {}) {
                                                                                  ^
src/./op_util.h:115:60: error: converting to ‘std::unordered_map<std::basic_string<char>, std::basic_string<char> >’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >]’
     std::unordered_map<std::string, std::string> kwarg = {}) {
                                                            ^
src/op_nn.cc: In lambda function:
src/op_nn.cc:352:57: error: converting to ‘std::unordered_map<std::basic_string<char>, std::basic_string<char> >’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >]’
                                {ograds[0], n->inputs[0]});

**Comment by xqdan** [comment]
I've found something related on stackoverflow, still don't know how to fix it.
http://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list

**Comment by xqdan** [comment]
when I switch to gcc-6.1, error gone, seems like a gcc's bug

**Comment by tqchen** [comment]
try to change this line https://github.com/tqchen/tinyflow/blob/master/src/op_util.h#L98
to 
```c++
std::unordered_map<std::string, std::string> kwarg = std::unoredered_map<std::string, std::string>()
```

**Comment by xqdan** [comment]
It works. Thanks.

**Comment by xqdan** [comment]
This patch works for me, can get libtinyflow.so in dir 'lib'.
 
diff --git a/Makefile b/Makefile
index dc56d3c..68de348 100644
--- a/Makefile
+++ b/Makefile
@@ -38,7 +38,7 @@ else
        NO_WHOLE_ARCH= --no-whole-archive
        CFLAGS  += -I$(TORCH_PATH)/install/include -I$(TORCH_PATH)/install/include/TH \
                           -I$(TORCH_PATH)/install/include/THC/
-       LDFLAGS += -L$(TORCH_PATH)/install/lib -lluajit -lluaT -lTH -lTHC
+        LDFLAGS += -L$(TORCH_PATH)/install/lib -lluajit -lluaT -lTH
 endif

 SRC = $(wildcard src/*.cc src/*/*.cc src/*/*/*.cc)
diff --git a/example/cifar_resnet.py b/example/cifar_resnet.py
old mode 100644
new mode 100755
diff --git a/example/mnist_lenet.py b/example/mnist_lenet.py
old mode 100644
new mode 100755
diff --git a/example/mnist_mlp_auto_shape_inference.py b/example/mnist_mlp_auto_shape_inference.py
old mode 100644
new mode 100755
diff --git a/example/mnist_softmax.py b/example/mnist_softmax.py
old mode 100644
new mode 100755
diff --git a/src/op_util.h b/src/op_util.h
index 9cd2279..a75ef76 100644
--- a/src/op_util.h
+++ b/src/op_util.h
@@ -95,7 +95,7 @@ inline void ParamParser(nnvm::NodeAttrs* attrs) {
 inline NodeEntry MakeNode(const char* op_name,
                           std::string node_name,
                           std::vector<NodeEntry> inputs,
-                          std::unordered_map<std::string, std::string> kwarg = {}) {
+                          std::unordered_map<std::string, std::string> kwarg = std::unordered_map<std::string, std::string>()) {
   NodePtr p = Node::Create();
   p->attrs.op = nnvm::Op::Get(op_name);
   p->attrs.name = std::move(node_name);
@@ -112,7 +112,7 @@ inline std::vector<NodeEntry> MakeBackwardGrads(
     const char* op_name,
     const NodePtr& n,
     std::vector<NodeEntry> inputs,
-    std::unordered_map<std::string, std::string> kwarg = {}) {
+    std::unordered_map<std::string, std::string> kwarg = std::unordered_map<std::string, std::string>()) {
   NodePtr p = Node::Create();
   p->attrs.op = nnvm::Op::Get(op_name);
   p->attrs.name = std::move(n->attrs.name + "_backward");

**Comment by tqchen** [comment]
please send a PR to patch the change to the master branch, thanks

**Comment by xqdan** [comment]
Sure, will do. Finally tinyflow ran successfully in my environment, also I'd like to share some experience later.

**Comment by xqdan** [comment]
1, torch install
  a)  http://torch.ch/docs/getting-started.html#_
  b) add 'export TORCH_HOME=/path/to/torch/' in your .bashrc

2, tinyflow install
   a), you may need to configure your git proxy:
       git config --global http.proxy "http://usr:pswd@IP:PORT"
       git config --global https.proxy "https://usr:pswd@IP:PORT"
   b) git clone https://github.com/tqchen/tinyflow.git ~/tinyflow --recursive
   c) cd ~/tinyflow; make; you may get a build error of this issue, can be fixed by Tianqi's code above
   d) in my torch installation, thers isn't libTHC.so, so I comment -lTHC in tinyflow's Makefile

3, run an example
   a) you may need to check if your http_proxy and https_proxy is configured correctly
   b) you may need to install missing python modules thru pip,
   c) if you using python 3, you need to modify "import cPickle" as "import _pickle as cPickle" in python/tinyflow/datasets.py line 5.
   d) run 'python3 example/mnist_softmax.py', you will get '[ 0.90920001]', I guess that means success
