### ISSUE TITLE
why set TBackwardNeedOutputs to True in nn_module?

### ISSUE THREAD

**Issue by tornadomeet** [tqchen/tinyflow#5]
op in `nn_module` group will own the same attr which has been set.  

and the line https://github.com/tqchen/tinyflow/blob/master/src/op_nn.cc#L97 set TBackwardNeedOutputs to be true so that  all ops with `.include("nn_module")` will need output when in `MakeNNBackwardNode`, but as we know, backwards calculation didn't depend the output value of fp node, only depend the output grad.

@tqchen

**Comment by tqchen** [comment]
It is really implementation dependent, for some modules, backward indeed dependent on output, for example backward of exp is likely using output instead of input.

This is a "safe" choice that can be override later by set this specifically in each op

**Comment by tornadomeet** [comment]
thanks, got it!
